ui: tape
browserify:
  - name: babelify
  - blacklist: regenerator
  - optional:
    - runtime
browsers:
  - name: chrome
    version: latest
  - name: safari
    version: latest
  - name: firefox
    version: latest
  - name: internet explorer
    version: latest
